config/routes.rb
WickedExample::Application.routes.draw do

  devise_for  :users, :controllers => { :registrations => "registrations" }

  root        :to => "pages#index"

  resources   :after_register

  resources   :users
  post '/save_biographical_data' => 'pages#save_biographical_data', as: 'save_biographical_data'
  
  post '/course_qualification_save' => 'pages#course_qualification_save', as: 'course_qualification_save'
  get '/course_qualification' => 'pages#course_qualification', as: 'course_qualification'
  
  post '/education_save_data' => 'pages#education_save_data', as: 'education_save_data'
  get '/education' => 'pages#education', as: 'education'
  
  post '/referral_data_save' => 'pages#referral_data_save', as: 'referral_data_save'
  get '/reference' => 'pages#reference', as: 'reference'
  
  get '/destroy_ref_data' => 'pages#destroy_ref_data', as: 'destroy_ref_data'
  get '/edit_referral_data' => 'pages#edit_referral_data', as: 'edit_referral_data'
  
  get '/destroy_ref_document' => 'pages#destroy_ref_document', as: 'destroy_ref_document'
  
  get '/supporting_document_save' => 'pages#supporting_document_save', as: 'supporting_document_save'
  get '/supporting_documents' => 'pages#supporting_documents', as: 'supporting_documents'

end

app/views/pages/_biographical_data.html.erb
<div id="course">
<ol class="breadcrumb">
  <li><a href="#">Home</a></li>
  <li><a href="#">Application</a></li>
  <li class="active">Biographical Data</li>
</ol>
<%= form_for @biographicaldata,:url=>save_biographical_data_path,:remote=>true ,:method=>"POST"  do |f| %>
<div class="clearfix">
   <%= f.label :first_name%>
  <div class="input">
    <%= f.text_field :first_name%>
  </div>
</div>

<div class="clearfix">
   <%= f.label :surname%>
  <div class="input">
    <%= f.text_field :surname %>
  </div>
</div>
<div class="clearfix">
   <%= f.label :initials%>
  <div class="input">
    <%= f.text_field :initials%>
  </div>
</div>

<div class="clearfix">
   <%= f.label :gender%>
  <div class="input">
      <%= f.radio_button :gender, 1, :checked => true %> Male	
    <%= f.radio_button :gender, 0 %> Female
  </div>
</div>

<div class="clearfix">
   <%= f.label :id_number%>
  <div class="input">
    <%= f.text_field :id_number%>
  </div>
</div>

<div class="clearfix">
   <%= f.label :mobile_no%>
  <div class="input">
    <%= f.text_field :mobile_no %>
  </div>
</div>



<div class="clearfix">
   <%= f.label :secondary_no%>
  <div class="input">
    <%= f.text_field :secondary_no%>
  </div>
</div>

<div class="clearfix">
   <%= f.label :done_before%>
  <div class="input">
    <%= f.radio_button :done_before, 1, :checked => true %> Yes
    <%= f.radio_button :done_before, 0 %> No
  </div>
</div>
<div class="clearfix">
   <%= f.label :last_assesment_date%>
  <div class="input">
    <%= f.text_field :last_assesment_date%>
  </div>
</div>

<div class="clearfix">
   <%= f.label :assesment_institution%>
  <div class="input">
    <%= f.text_field :assesment_institution %>
  </div>
</div>




<div class="form-actions">
  <button class="btn primary" type="submit">Save</button> 
</div>
<% end %>

</div>

app/views/pages/_course_qualification.html.erb
<ol class="breadcrumb">
  <li><a href="#">Home</a></li>
  <li><a href="#">Application</a></li>
  <li ><a href="#">Biographical Data</a></li>
   <li class="active">Course</li>
</ol>

<%= form_for @course,:url=>course_qualification_save_path,:remote=>true ,:method=>"POST" do |f| %>
<div class="clearfix">
   <%= f.label :educational_institution%>
  <div class="input">
    <%= f.text_field :educational_institution%>
    <%= f.select :educational_institution, options_for_select([["University ABC" , "University ABC" ],["University  DCA" , "University  DCA" ]]) %>
  </div>
</div>

<div class="clearfix">
   <%= f.label :course_reapplied%>
  <div class="input">
    <%= f.select :course_reapplied, options_for_select([["Maths" , "Maths" ],["English" , "English" ]]) %>
  </div>
</div>
<div class="clearfix">
   <%= f.label :region%>
  <div class="input">
    <%= f.text_field :region %>
  </div>
</div>

<div class="clearfix">
   <%= f.label :field_of_study%>
  <div class="input">
    <%= f.text_field :field_of_study%>
  </div>
</div>
<%= hidden_field_tag "biographical_data_id", @biographicaldata.id %>
<div class="form-actions">

 
  
  <button class="btn primary" type="submit">Save</button> 
</div>
<% end %>
 <button class="btn primary back_1" type="submit" style="margin-left: 373px; margin-top: -140px;">back</button> 


 <script>
  $(document).ready(function(){
    $(".back_1").click(function(){
        $.ajax({
            type : 'GET',
            url : '<%= root_path%>',
            data: {'id' : "<%=@biographicaldata.id %>"},
             success: function () {
             }
           })
     });
  }); 
 </script> 

app/views/pages/_form_application.html.erb
<ol class="breadcrumb">
  <li><a href="#">Home</a></li>
  <li><a href="#">Application</a></li>
  <li ><a href="#">Biographical Data</a></li>
  <li ><a href="#">Course</a></li>
  <li ><a href="#">Education</a></li>
  <li ><a href="#">Refrences</a></li>
  <li ><a href="#">Check</a></li>
  <li class="active">Confirm</a></li>
</ol>

<p>Hi Download your Invoice to make the payment<p>


<button class="btn primary" type="submit" >submit</button>

app/views/pages/_refrence.html.erb
<ol class="breadcrumb">
  <li><a href="#">Home</a></li>
  <li><a href="#">Application</a></li>
  <li ><a href="#">Biographical Data</a></li>
  <li ><a href="#">Course</a></li>
  <li ><a href="#">Education</a></li>
  <li class="active">Refrences</a></li>
</ol>
<table class="table">
<tr>
<th>Refrences Activity Descritpion </th>
<th></th>
<th></th>
</tr>
<% @education_refrences.each do |refrences| %>
<tr>
<td><%=refrences.activity_description_place %></td>
<td><%=link_to "Edit", edit_referral_data_path(:ref_id=>refrences.id, :education_id => @education.id ), :remote=>true %></td>
<td><%=link_to "Delete", destroy_ref_data_path(:ref_id=>refrences.id, :education_id => @education.id ), :confirm => 'Are you sure?', :remote=>true  %></td>
</tr>
<% end %>
</table>

<%= form_for @refrence,:url=>referral_data_save_path,:method=>:get,:remote=>true do |f| %>
<div class="clearfix">
   <%= f.label :activity_description_place %>
  <div class="input">
    <%= f.text_area :activity_description_place,:rows=>5,:cols=>40%>
  </div>
</div>

<div class="clearfix">
   <%= f.label :expirience_from_activity%>
  <div class="input">
    <%= f.text_area :expirience_from_activity,:rows=>5,:cols=>40 %>
  </div>
</div>
<div class="clearfix"  >
 <%= f.label :skill_1%>
<%= f.select 'skill_1', options_for_select([["Programming" , "Programming" ],["Communication" , "Communication" ],["Art" , "Art" ]])%>
</div>

<div class="clearfix"  style="margin-left: 290px; margin-top: -67px;">
   <%= f.label :skill_1_description%>
  <div class="input">
    <%= f.text_field :skill_1_description%>
  </div>
</div>

<div class="clearfix"  >
 <%= f.label :skill_2%>
<%= f.select 'skill_2', options_for_select([["Programming" , "Programming" ],["Communication" , "Communication" ],["Art" , "Art" ]])%>
</div>

<div class="clearfix" style="margin-left: 290px; margin-top: -67px;">
   <%= f.label :skill_2_description%>
  <div class="input">
    <%= f.text_field :skill_2_description%>
  </div>
</div>
<div class="clearfix"  >
 <%= f.label :skill_3%>
<%= f.select 'skill_3', options_for_select([["Programming" , "Programming" ],["Communication" , "Communication" ],["Art" , "Art" ]])%>
</div>

<div class="clearfix" style="margin-left: 290px; margin-top: -67px;">
   <%= f.label :skill_3_description%>
  <div class="input">
    <%= f.text_field :skill_3_description%>
  </div>
</div>
<%= hidden_field_tag "education_id", @education.id %>
<%= hidden_field_tag "ref_id", @refrence.id %>
<div class="form-actions">

  

  <button class="btn primary" type="submit">Save</button> 
</div>
<% end %>

  <button class="btn primary back_3" type="submit" style="margin-left: 373px; margin-top: -140px;">back</button> 

  <button class="btn primary" type="submit" id="next" style="margin-left: 373px; margin-top: -140px;">Next</button>



  <script>
	$(document).ready(function(){
	  $("#next").click(function(){
	      $.ajax({
            type : 'GET',
            url : '<%= referral_data_save_path%>',
            data: {'next' : true},
             success: function () {
             }
           })
	   });

    $(".back_3").click(function(){
    $.ajax({
      type : 'POST',
      url : '<%= save_education_data_path%>',
      data: {'education_back_id' : "<%=@education.id%>"},
        success: function () {
        }
      })
    });
	}); 
 </script> 

app/views/pages/course_qualification.html.erb
<ol class="breadcrumb">
  <li><a href="#">Home</a></li>
  <li><a href="#">Application</a></li>
  <li ><a href="#">Biographical Data</a></li>
   <li class="active">Course</li>
</ol>

<%= form_for @course,:url=>course_qualification_save_path,:method=>"POST" do |f| %>
<div class="clearfix">
   <%= f.label :educational_institution%>
  <div class="input">
    <%= f.text_field :educational_institution%>
    <%= f.select :educational_institution, options_for_select([["University ABC" , "University ABC" ],["University  DCA" , "University  DCA" ]]) %>
  </div>
</div>

<div class="clearfix">
   <%= f.label :course_reapplied%>
  <div class="input">
    <%= f.select :course_reapplied, options_for_select([["Maths" , "Maths" ],["English" , "English" ]]) %>
  </div>
</div>
<div class="clearfix">
   <%= f.label :region%>
  <div class="input">
    <%= f.text_field :region %>
  </div>
</div>

<div class="clearfix">
   <%= f.label :field_of_study%>
  <div class="input">
    <%= f.text_field :field_of_study%>
  </div>
</div>
<%= hidden_field_tag "biographical_data_id", @biographicaldata.id %>
<div class="form-actions">

 
  
  <button class="btn primary" type="submit">Save</button> 
</div>
<% end %>
<%= link_to "Back", root_path(id: @biographicaldata.id), :class=>"btn primary", :style=>"margin-left: 373px; margin-top: -140px;"%>

app/views/pages/education.html.erb
<ol class="breadcrumb">
  <li><a href="#">Home</a></li>
  <li><a href="#">Application</a></li>
  <li ><a href="#">Biographical Data</a></li>
  <li ><a href="#">Course</a></li>
  <li class="active">Education</a></li>
</ol>
<%= form_for  @education, :url=>education_save_data_path, :method=>"POST" do |f| %>
  <div class="clearfix">
     <%= f.label :completion_year%>
    <div class="input">
      <%= f.text_field :completion_year%>
    </div>
  </div>

  <div class="clearfix">
     <%= f.label :completed_qualification%>
    <div class="input">
      <%= f.text_field :completed_qualification %>
    </div>
  </div>
  <div class="clearfix">
     <%= f.label :final_result%>
    <div class="input">
      <%= f.select :final_result, options_for_select([["Pass" , "Pass" ],["Fail" , "Fail" ]]) %>
    </div>
  </div>

  <div class="clearfix">
     <%= f.label :endorsment%>
    <div class="input">
      <%= f.text_field :endorsment%>
    </div>
  </div>

  <div class="sub_mark">
    <div class="clearfix">
       <%= f.label :subject_1%>
      <div class="input">
        <%= f.text_field :subject_1%>
      </div>
    </div>

    <div class="clearfix" style="margin-left: 290px; margin-top: -61px;" >
      <%= f.label :mark_1%>
      <%= f.select 'mark_1', options_for_select([["60-70" , "60-70" ],["71-80" , "71-80" ],["81-90" , "81-90" ]])%>
    </div>
  </div>

  <div class="sub_mark">
    <div class="clearfix">
       <%= f.label :subject_2%>
      <div class="input">
        <%= f.text_field :subject_2%>
      </div>
    </div>

    <div class="clearfix" style="margin-left: 290px; margin-top: -61px;" >
     <%= f.label :mark_2%>
    <%= f.select 'mark_2', options_for_select([["60-70" , "60-70" ],["71-80" , "71-80" ],["81-90" , "81-90" ]])%>
    </div>
  </div>

  <div class="sub_mark">
    <div class="clearfix">
       <%= f.label :subject_3%>
      <div class="input">
        <%= f.text_field :subject_3%>
      </div>
    </div>

    <div class="clearfix" style="margin-left: 290px; margin-top: -61px;" >
      <%= f.label :mark_3%>
      <%= f.select 'mark_3', options_for_select([["60-70" , "60-70" ],["71-80" , "71-80" ],["81-90" , "81-90" ]])%>
    </div>
  </div>

  <div class="sub_mark">
    <div class="clearfix">
       <%= f.label :subject_4%>
      <div class="input">
        <%= f.text_field :subject_4%>
      </div>
    </div>

    <div class="clearfix" style="margin-left: 290px; margin-top: -61px;" >
      <%= f.label :mark_4%>
      <%= f.select 'mark_4', options_for_select([["60-70" , "60-70" ],["71-80" , "71-80" ],["81-90" , "81-90" ]])%>
    </div>
  </div>

  <div class="sub_mark">
    <div class="clearfix">
       <%= f.label :subject_5%>
      <div class="input">
        <%= f.text_field :subject_5%>
      </div>
    </div>
    <div class="clearfix" style="margin-left: 290px; margin-top: -61px;" >
      <%= f.label :mark_5%>
      <%= f.select 'mark_5', options_for_select([["60-70" , "60-70" ],["71-80" , "71-80" ],["81-90" , "81-90" ]])%>
    </div>
  </div>

  <div class="sub_mark">
    <div class="clearfix">
       <%= f.label :subject_6%>
      <div class="input">
        <%= f.text_field :subject_6%>
      </div>
    </div>

    <div class="clearfix" style="margin-left: 290px; margin-top: -61px;" >
      <%= f.label :mark_6%>
      <%= f.select 'mark_6', options_for_select([["60-70" , "60-70" ],["71-80" , "71-80" ],["81-90" , "81-90" ]])%>
    </div>
  </div>

  <div class="sub_mark">
    <div class="clearfix">
       <%= f.label :subject_7%>
      <div class="input">
        <%= f.text_field :subject_7%>
      </div>
    </div>

    <div class="clearfix" style="margin-left: 290px; margin-top: -61px;" >
      <%= f.label :mark_7%>
      <%= f.select 'mark_7', options_for_select([["60-70" , "60-70" ],["71-80" , "71-80" ],["81-90" , "81-90" ]])%>
    </div>
  </div>

  <div class="sub_mark">
    <div class="clearfix">
       <%= f.label :subject_8%>
      <div class="input">
        <%= f.text_field :subject_8%>
      </div>
    </div>

    <div class="clearfix" style="margin-left: 290px; margin-top: -67px;" >
      <%= f.label :mark_8%>
      <%= f.select 'mark_8', options_for_select([["60-70" , "60-70" ],["71-80" , "71-80" ],["81-90" , "81-90" ]])%>
    </div>
  </div>

  <div class="sub_mark">
    <div class="clearfix">
       <%= f.label :subject_9%>
      <div class="input">
        <%= f.text_field :subject_9%>
      </div>
    </div>

    <div class="clearfix" style="margin-left: 290px; margin-top: -61px;" >
     <%= f.label :mark_9%>
    <%= f.select 'mark_9', options_for_select([["60-70" , "60-70" ],["71-80" , "71-80" ],["81-90" , "81-90" ]])%>
    </div>
  </div>


  <%= f.file_field :document %>
  <%= hidden_field_tag "course_id", @course.id %>

  <div class="form-actions">
    <button class="btn primary" type="submit" >Save</button> 
  </div>
  
<% end %>

<%= link_to "Back", course_qualification_path(course_back_id: @course.id), :class=>"btn primary", :style=>"margin-left: 373px; margin-top: -140px;"%>

app/views/pages/index.html.erb
<% if user_signed_in? %>
<div id="course">
<ol class="breadcrumb">
  <li><a href="#">Home</a></li>
  <li><a href="#">Application</a></li>
  <li class="active">Biographical Data</li>
</ol>
<%= form_for @biographicaldata,:url=>save_biographical_data_path,:method => "POST" do |f| %>
<div class="clearfix">
   <%= f.label :first_name%>
  <div class="input">
    <%= f.text_field :first_name%>
  </div>
</div>

<div class="clearfix">
   <%= f.label :surname%>
  <div class="input">
    <%= f.text_field :surname %>
  </div>
</div>
<div class="clearfix">
   <%= f.label :initials%>
  <div class="input">
    <%= f.text_field :initials%>
  </div>
</div>

<div class="clearfix">
   <%= f.label :gender%>
  <div class="input">
      <%= f.radio_button :gender, 1, :checked => true %> Male	
    <%= f.radio_button :gender, 0 %> Female
  </div>
</div>

<div class="clearfix">
   <%= f.label :id_number%>
  <div class="input">
    <%= f.text_field :id_number%>
  </div>
</div>

<div class="clearfix">
   <%= f.label :mobile_no%>
  <div class="input">
    <%= f.text_field :mobile_no %>
  </div>
</div>



<div class="clearfix">
   <%= f.label :secondary_no%>
  <div class="input">
    <%= f.text_field :secondary_no%>
  </div>
</div>

<div class="clearfix">
   <%= f.label :done_before%>
  <div class="input">
    <%= f.radio_button :done_before, 1, :checked => true %> Yes
    <%= f.radio_button :done_before, 0 %> No
  </div>
</div>
<div class="clearfix">
   <%= f.label :last_assesment_date%>
  <div class="input">
    <%= f.text_field :last_assesment_date%>
  </div>
</div>

<div class="clearfix">
   <%= f.label :assesment_institution%>
  <div class="input">
    <%= f.text_field :assesment_institution %>
  </div>
</div>




<div class="form-actions">
  <button class="btn primary" type="submit">Save</button> 
</div>
<% end %>

</div>

<% else %>
<h2>welcome</h2>

<% end %>

app/views/pages/index.js.erb
$("#course").html("<%= escape_javascript(render(:partial => 'biographical_data')) %>");

app/views/pages/reference.html.erb
<ol class="breadcrumb">
  <li><a href="#">Home</a></li>
  <li><a href="#">Application</a></li>
  <li ><a href="#">Biographical Data</a></li>
  <li ><a href="#">Course</a></li>
  <li ><a href="#">Education</a></li>
  <li class="active">Refrences</a></li>
</ol>


<table class="table">
<tr>
<th>Refrences Activity Descritpion </th>
<th></th>
<th></th>
</tr>
<% @education_refrences.each do |refrences| %>
<tr>
<td><%=refrences.activity_description_place %></td>
<td><%=link_to "Edit", reference_path(:ref_id=>refrences.id, :education_id => @education.id ) %></td>
<td><%=link_to "Delete", destroy_ref_data_path(:ref_id=>refrences.id, :education_id => @education.id ), :confirm => 'Are you sure?'  %></td>
</tr>
<% end %>
</table>

<%= form_for @refrence,:url=>referral_data_save_path,:method=>:post, :html => { :multipart => true } do |f| %>
<div class="clearfix">
   <%= f.label :activity_description_place %>
  <div class="input">
    <%= f.text_area :activity_description_place,:rows=>5,:cols=>40%>
  </div>
</div>

<div class="clearfix">
   <%= f.label :expirience_from_activity%>
  <div class="input">
    <%= f.text_area :expirience_from_activity,:rows=>5,:cols=>40 %>
  </div>
</div>
<div class="clearfix"  >
 <%= f.label :skill_1%>
<%= f.select 'skill_1', options_for_select([["Programming" , "Programming" ],["Communication" , "Communication" ],["Art" , "Art" ]])%>
</div>

<div class="clearfix"  style="margin-left: 290px; margin-top: -67px;">
   <%= f.label :skill_1_description%>
  <div class="input">
    <%= f.text_field :skill_1_description%>
  </div>
</div>

<div class="clearfix"  >
 <%= f.label :skill_2%>
<%= f.select 'skill_2', options_for_select([["Programming" , "Programming" ],["Communication" , "Communication" ],["Art" , "Art" ]])%>
</div>

<div class="clearfix" style="margin-left: 290px; margin-top: -67px;">
   <%= f.label :skill_2_description%>
  <div class="input">
    <%= f.text_field :skill_2_description%>
  </div>
</div>
<div class="clearfix"  >
 <%= f.label :skill_3%>
<%= f.select 'skill_3', options_for_select([["Programming" , "Programming" ],["Communication" , "Communication" ],["Art" , "Art" ]])%>
</div>

<div class="clearfix" style="margin-left: 290px; margin-top: -67px;">
   <%= f.label :skill_3_description%>
  <div class="input">
    <%= f.text_field :skill_3_description%>
  </div>
</div>
<%= hidden_field_tag "education_id", @education.id %>
<%= hidden_field_tag "ref_id", @refrence.id %>

<%= file_field_tag "ref_document[]" , :multiple=>true%>
<div id="document_div">
  <% if !@attached_files.nil? %>
    <table class="table">
      <tr>
        <th>Upload Name </th>
        <th></th>
        <th></th>
      </tr>
      <% @attached_files.each do |attached_files| %>
        <tr>
          <td><%= attached_files.ref_document_file_name %></td>
          <td></td>
          <td><%=link_to "Delete", destroy_ref_document_path(:file_id => attached_files.id, :education_id => @education.id), :confirm => 'Are you sure?'  %></td>
        </tr>
      <% end %>
    </table>
  <% end %>
</div>

<div class="form-actions">
  <button class="btn primary" type="submit">Save</button> 
</div>
<% end %>
<%= link_to "Back", education_path(education_id: @education.id), :class=>"btn primary", :style=>"margin-left: 373px; margin-top: -140px;"%>

<%= link_to "Next", supporting_documents_path, :class=>"btn primary", :style=>"margin-left: 373px; margin-top: -140px;"%>

app/views/pages/supporting_document_save.js.erb
$("#supporting_document").html("<%= escape_javascript(render(:partial => 'form_application')) %>");

app/views/pages/supporting_documents.html.erb
<div id = "supporting_document">
	<ol class="breadcrumb">
	  <li><a href="#">Home</a></li>
	  <li><a href="#">Application</a></li>
	  <li ><a href="#">Biographical Data</a></li>
	  <li ><a href="#">Course</a></li>
	  <li ><a href="#">Education</a></li>
	  <li ><a href="#">Refrences</a></li>
	  <li class="active">Check</a></li>
	</ol>


	<%= form_tag supporting_document_save_path,:method=>:get, :remote=>true do  %>

	<table class="table">
	<tr>
	<th>Document name </th>
	<th>Document Given</th>
	<th>Certified</th>
	</tr>
	<% @documents.each do |document| %>
	<tr>
	<td><%=document.name%></td>
	<td> <%= check_box_tag "document_given[]",document.id %><label>Document given</label>
	</td>
	<td><%= check_box_tag "certified[]" ,document.id %><label>Certified</label></td>
	</tr>
	<% end %>
	</table>

	<div class="form-actions">
	  <button class="btn primary" type="submit">Save</button> 
	</div>
	<% end %>
</div>